language: node_js
node_js:
  - "10.15.3"

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href="/componentSample/"

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: AKIAIOBTPU4WZQ2WS3JQ
    secret_access_key: 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
    application: 	componentSample
    deployment_group: 	componentSample
    region: ap-northeast-1
