language: node_js
node_js:
  - "10.15.3"
script:
  - npm run test
  - npm run lint
  - npm run e2e

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js