language: node_js
node_js:
  - "10.15.3"

dist: trusty

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - master

notifications:
  flowdock:
    secure: "tSjMLbGqqLMvaZa3r/T4ybAtF5sM2bqJZH0Yxqmp+C4z2aUxY68njy/BfrBb4zSFe6CKPQHvz0PJ7UN3H5PiEEA88Jem7AUNbYf4WdPE7th6VIzU4uqF7bxJmgIxAFMDAc5M6Q7j8VPkM20SJOkwcf9iTO5q+3y0JxtlK4++MZ23kJcIIUYBM9qtRrJwF+FQp4y3K4GHQJ8xqU7o7ZiUgcL17dFN07ASbMqUz4cPbzeOEbL6VCF/cIZZsbgalCXMNuy2sVf3nsEq54T/3YxQI7HhsuHn1uW4gTySy1CzMDRv/zeUWX8C6Y8WZq0yl6e+XyvYGHdKA1mJim06NubOgyp9l1ShfXT9qbFndyTdW1erIHPOVVjoraQT/lKhESPKUvdO1SahE6Pa0JkoL9eYAyLfEsc/wH4Ur1iOcRjjuRXwmq1xDHQUmCxU5HGB4RQ659WkxC9Xt1nNadUlVmC/wmpOpPWgs00UfesdFJYguj4nGAfhargnfdmiJhGotCYqw5weJ/e75OwQYNiiYvble9EQeRxrUCR9Db0ujWoIngecKQmwS0z15ciftLe+VclnKXddl6C9ANMODXMeMm3CFG9kgCEwV5HbLI7lm4Hy776GvXJR1zLDQpYlUQBzi+5QtDEiAvCn+zH8TjYE17yVHgWSLRyS90xlG8EQ2xkA7uU="


before_install:
  - chmod 555 ./scripts/deploy.sh
  - npm install -g @angular/cli
  # karma for travis
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - webdriver-manager update

before_script:
  - ng lint
  - ng test --code-coverage
  - ng e2e --protractor-config='e2e/protractor.conf.js'

script:
  - ng build --prod --base-href="/componentSample/"

after_success:
  # - npm install coveralls
  # - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash scripts/deploy.sh

after_failure:

after_script:

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: report
  # local_dir: dist/componentSample
  on:
    branch: master

env:
  global:
  - GH_REF: github.com/m-sugizaki/tmpRepository.git
 